---
# handlers file for ../linux_hardening_V3.2_testing/TestingRole
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
- name: Reload_sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

####
- name: Restart_postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
    
- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded

- name: Restart systemd-journal-upload
  systemd:
    name: systemd-journal-upload
    state: restarted

- name: Restart_sshd_mac
  systemd: 
    name: sshd
    state: restarted

- name: Restart_rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Update_authselect
  ansible.builtin.command: authselect apply-changes
  changed_when: true

