---
# handlers file for ./mcx_hardening_6_role

  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes


  - name: Restart_rsyslog
    ansible.builtin.service:
      name: rsyslog
      state: restarted
