---
# handlers file for ../linux_hardening_V3.2_testing/TestingRole
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart_sshd_mac
  ansible.builtin.systemd:
    name: sshd
    state: reloaded

- name: Restart_sshd
  systemd:
    name: sshd
    state: restarted

